"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import IconButton from "@mui/material/IconButton";
import Typography from "@mui/material/Typography";
import Menu from "@mui/material/Menu";
import MenuIcon from "@mui/icons-material/Menu";
import Container from "@mui/material/Container";
import Button from "@mui/material/Button";
import MenuItem from "@mui/material/MenuItem";
import Link from "next/link";
import { ThemeProvider } from "@emotion/react";
import { createTheme } from "@mui/material";
const pages = ["Home", "Product", "Help", "Services"];
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Home Page ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [anchorElNav, setAnchorElNav] = React.useState(null);
  const [anchorElUser, setAnchorElUser] = React.useState(null);
  const handleOpenNavMenu = (event) => {
    setAnchorElNav(event.currentTarget);
  };
  const handleOpenUserMenu = (event) => {
    setAnchorElUser(event.currentTarget);
  };

  const handleCloseNavMenu = () => {
    setAnchorElNav(null);
  };

  const handleCloseUserMenu = () => {
    setAnchorElUser(null);
  };

  const theme = createTheme({
    typography: {
      fontFamily: ["pacifico", "poppins"],
    },
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <AppBar
            position="sticky"
            sx={{
              top: 0,
              background: "#111",
              color: "#5d9baa",
              fontFamily: "pacifico",
            }}
          >
            <Container maxWidth="xl">
              <Toolbar disableGutters>
                <img src="/image/logo.png" alt="Logo " width={60} height={60} />
                <Typography
                  variant="h6"
                  noWrap
                  component="a"
                  href="/"
                  sx={{
                    mr: 30,
                    display: { xs: "none", md: "flex" },
                    fontWeight: 700,
                    letterSpacing: ".2rem",
                    color: "#1976d2",
                    textDecoration: "none",
                    fontFamily: "pacifico",
                    textTransform: "uppercase",
                  }}
                >
                  NABIH
                </Typography>
                {/*  RESPONSIVE SECTION OF NAVBAR */}
                <Box
                  sx={{
                    background: "#101010",
                    flexGrow: 1,
                    display: { xs: "flex", md: "none" },
                  }}
                >
                  <IconButton
                    size="large"
                    aria-label="account of current user"
                    aria-controls="menu-appbar"
                    aria-haspopup="true"
                    onClick={handleOpenNavMenu}
                    color="inherit"
                  >
                    <MenuIcon />
                  </IconButton>
                  <Menu
                    id="menu-appbar"
                    anchorEl={anchorElNav}
                    anchorOrigin={{
                      vertical: "bottom",
                      horizontal: "left",
                    }}
                    keepMounted
                    transformOrigin={{
                      vertical: "top",
                      horizontal: "left",
                    }}
                    open={Boolean(anchorElNav)}
                    onClose={handleCloseNavMenu}
                    sx={{
                      display: { xs: "block", md: "none" },
                    }}
                  >
                    {pages.map((page, index) => {
                      {
                        /* الطريقة التقليدية لاضافة اللينك المناسب  */
                      }
                      // قم بفحص إذا كانت الصفحة هي "Product" أم لا
                      {
                        /* const isProductPage = page === "Product";

                      // قم بتحديد الـ href بناءً على الشرط
                      const href = isProductPage ? "/components/product" : "/"; */
                      }
                      {
                        /* === انهاء الطريقة الاولي التقليدية=== */
                      }

                      {
                        /* الطريقة الثانية الخاصة بال Regular expression */
                      }

                      // استخدم Regex لتحديد ما إذا كانت كلمة "Product" موجودة في اسم الصفحة
                      const isProductPage = /Product/i.test(page);
                      // تحديد الرابط باستخدام الRegex
                      const href = isProductPage ? "/components/product" : "/";
                      return (
                        <MenuItem
                          style={{ background: "#101010", color: "white" }}
                          key={index}
                          onClick={handleCloseNavMenu}
                        >
                          <Typography fontWeight={"bold"} textAlign="center">
                            <Link href={href}>{page}</Link>
                          </Typography>
                        </MenuItem>
                      );
                    })}
                  </Menu>
                </Box>
                {/* == END RESPONSIVE SECTION OF NAVBAR == */}

                <Box sx={{ flexGrow: 1, display: { xs: "none", md: "flex" } }}>
                  <Link href={"/"}>
                    <Button
                      className="hoverClass"
                      style={{ fontFamily: "pacifico", letterSpacing: "3px" }}
                      onClick={handleCloseNavMenu}
                      sx={{ my: 2, color: "white", display: "block" }}
                    >
                      Home
                    </Button>
                  </Link>
                  <Link href={"/components/product"}>
                    <Button
                      className="hoverClass"
                      style={{ fontFamily: "pacifico", letterSpacing: "3px" }}
                      onClick={handleCloseNavMenu}
                      sx={{ my: 2, color: "white", display: "block" }}
                    >
                      products
                    </Button>
                  </Link>

                  <Button
                    className="hoverClass"
                    style={{ fontFamily: "pacifico", letterSpacing: "3px" }}
                    onClick={handleCloseNavMenu}
                    sx={{ my: 2, color: "white", display: "block" }}
                  >
                    Help
                  </Button>
                  <Button
                    className="hoverClass"
                    style={{ fontFamily: "pacifico", letterSpacing: "3px" }}
                    onClick={handleCloseNavMenu}
                    sx={{ my: 2, color: "white", display: "block" }}
                  >
                    Services
                  </Button>
                </Box>
                
              </Toolbar>
            </Container>
          </AppBar>
        </ThemeProvider>

        {children}
      </body>
    </html>
  );
}
